### ISSUE TITLE
Mutual authentication in trust management specs

### ISSUE THREAD

**Issue by KCorre** [reTHINK-project/specs#3]
Hi @Ricardo-Chaves @sbecot @jmcrom 

The specs here describe a mutual authentication mechanism bounding authentication to a key exchange mechanism. These keys are then used to encrypt communication between Alice and Bob. 
https://github.com/reTHINK-project/specs/tree/master/trust-management

It is pretty similar to what is done in WebRTC. The reason is that during our discussion in Paris I proposed to use the same solution. However I did not think about the actual use cases that would requires this spec/implementation. 

The issue is the following: is there any reason to not use directly (or adapt) WebRTC data channel to allow hyperty p2p data communication? It also means that we would use WebRTC media for p2p media communications.

**Comment by antonroman** [comment]
Hi @KCorre,
the use of Datachannel for a P2P is being discussed here https://github.com/reTHINK-project/dev-runtime-core/issues/103 for phase 2 of WP3. So your proposal makes all the sense.
