### ISSUE TITLE
Reusage of Hyperty and Data Object URLs

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/specs#6]
https://github.com/reTHINK-project/dev-runtime-core/issues/85 follow up.

In order to improve performance and avoid performing the creation / subscription process everytime there is a new session, the data object URL persisted in the Domain Registry should be reused and allocated to the object.

Also, Hyperty addresses don't have to be reallocated for every new runtime session

At the end, this means the runtime registry should:
- use the Persistence Manager to store locally Hyperties and Data Objects registry entries.
- when the runtime is closed, the addresses are not deallocated from the Message Node Address Allocation and Domain Registry entries are updated with status = disconnected

and the Sync Manager uses the Persistence Manager to store locally all [subscriptions](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/syncher/Subscription.js).

Hyperty URLs reusage:
- during the [Hyperty registration procedure](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/basics/register-hyperty.md),  after identity is associated with the Hyperty (steps 2-3), the Registry will check in its local storage registry if there is a valid Hyperty registry entry to be used for such Hyperty descriptor URL. If yes, steps 5 - 16 are skipped and the Hyperty instance registration is updated with an Update message and not with a Create Message. Should we only allow registry updates for the same identity / guid?

Data Object URLs reusage:
- as soon as the Sync Manager is instantiated by the Runtime UA it reactivates all [subscriptions](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/syncher/Subscription.js). In this way updates performed on reporters will be immediatly propagated to authorised observers.
- during the [creation of a data object](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/data-sync/data-object-creation.md) in step 1 and 3, allow adding a URL to be used for data object. The registry should check the identity / guid associated to the reporter is the same the previous one. In that case, steps 5 -10, 15 - 19 are skipped.

**Comment by sdruesedow** [comment]
This also requires extensions on the MN side, since the MNs maintain lists of allocated addresses and subscriptions which are not persistent yet.

**Comment by pchainho** [comment]
The runtime identifier should also be reused between different runtime sessions

**Comment by pchainho** [comment]
The MN subscriptions should be always persisted even without the reusage of Hyperty and Object addresses to avoid loosing subscription when the MN reboot in the middle of the runtime session
